### ISSUE TITLE
Error while moving file '"file.jpg"' to trash: Remove { code: Some(1) }

### ISSUE THREAD

**Issue by rofrol** [ArturKovacs/emulsion#163] opened 2020-12-25 18:09 UTC
Got this error when tried to remove some file.

Installed with `cargo install emulsion --features=networking`

**Comment by ArturKovacs** [comment] 2020-12-26 09:39
Hi! Welcome and thanks for opening an issue. 

Which desktop environment (e.g. Gnome, Kde) and what version did you use when encountering this?

**Comment by rofrol** [comment] 2020-12-26 18:29
```bash
$ cargo install emulsion --features=networking
...
$ emulsion --version
emulsion 7.2.0
$ ldd ~/.cargo/bin/emulsion 
	linux-vdso.so.1 (0x00007ffc2d3c4000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fd042213000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd04220d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd0421f2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd042008000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd041eb9000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd041eae000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd041e8a000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fd041e84000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fd041e7c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd042a37000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fd041e62000)
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.10
DISTRIB_CODENAME=groovy
DISTRIB_DESCRIPTION="Ubuntu 20.10"
$ uname -a
Linux roman-MS-7B43 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/roman/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.48.0 (7eac88abb 2020-11-16)
$ apt policy gnome
gnome:
  Installed: (none)
  Candidate: 1:3.30+3
  Version table:
     1:3.30+3 500
        500 http://pl.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
```

**Comment by ArturKovacs** [comment] 2020-12-28 11:29
I installed a fresh Ubuntu 20.10 on a VM, selecting "Minimal Installation" and it works for me.

Could you check if you have `gio`, by for example running
```
gio --version
```
The trashing functionality requires the presence of an appropriate command line utility that's able to move items to the trash. On GNOME (Ubuntu) this is `gio`.

Note: I had to compile from the `add-nix` branch as that fixes shader errors that happen with the Virtual Box VMSVGA video driver. These changes will soon be merged into master.

**Comment by ArturKovacs** [comment] 2020-12-31 16:26
@akimdi also experienced this error. Quoting their description from [their comment](https://github.com/ArturKovacs/emulsion/pull/164#issuecomment-752750084):

> Not everywhere can create .Trash-1000 folder. For example, cannot do it in my ram folder I suspect that this is due to access rights. Other apps can do this.
> 
>```Error while moving file '"1.jpg"' to trash: Remove { code: Some(1) }```

**Comment by ArturKovacs** [comment] 2021-01-26 22:31
I have a feeling that this is caused by the incorrect path resolution in `trash` which had fix deployed in https://github.com/ArturKovacs/trash-rs/commit/5dfe5dc0beaa29a537808d017e5852ad976644e4

I haven't attempted to reproduce this yet, but I'll look at this again later.

**Comment by akimdi** [comment] 2021-03-29 16:14
is'n working
https://github.com/ArturKovacs/trash-rs/commit/5dfe5dc0beaa29a537808d017e5852ad976644e4

but maybe i'm doing something wrong?

**Comment by ArturKovacs** [comment] 2021-04-11 11:39
Using Xubuntu 20.04 I created a tpmfs by adding this to my `/etc/fstab`
```
tmpfs  /home/artur/mem    tmpfs  rw,nodev,nosuid,size=1G  0  0
```

Then I copied an image to the `mem` folder and, using a simple test program using `trash` directly, I tried deleting the image and got the same error. 

The trash implementation was using `gio`, so I tried executing `gio` directly which resulted in this:
```
$ gio trash '/home/artur/mem/hello_world.png' 
gio: file:///home/artur/mem/hello_world.png: Trashing on system internal mounts is not supported
```

If I try deleting the file with the default file manager, thunar, I'm only offered to delete the file permanently, which indicates to me that it's simply not possible to trash files on such a filesystem.

I think that emulsion should not automatically remove the file permanently. I'm also not inclined to implement any kind of user interaction for this case, but I'll leave this issue open because I believe that it would be reasonable to at least provide a more descriptive error message in this case.

**Comment by akimdi** [comment] 2021-04-14 18:17
Yes, you're right.
I have now installed thunar and I'm getting the same behavior. I use nnn and it moves files to the trash.

nnn uses the [trash-cli](https://github.com/andreafrancia/trash-cli)

Since september 26, 2020, nnn supports [gio trash](https://github.com/jarun/nnn/issues/740)

It turns out that they [work differently in different file systems](https://youtu.be/2QNeETIiXs0)

P.S. gio certainly does a worse job than trash-cli 😥️

**Comment by ArturKovacs** [comment] 2021-04-14 18:32
The `trash` crate actually has a fully rust implementation of the freedesktop.org trash specification on the [`v2-dev`](https://github.com/ArturKovacs/trash-rs/tree/v2-dev) branch, maybe I should just replace the current implementation with that. 🤔

**Comment by akimdi** [comment] 2021-04-14 18:44
I tried to change the behavior of emulation.
I wrote the following in the config file.

https://github.com/akimdi/emulsion/blob/master/cfg.toml#L14

https://github.com/akimdi/emulsion/blob/master/cfg.toml#L29

And I got this error, although emulsion still created .Trash-1000 folder  and put a file in it, but emulsion froze.

![1618425113](https://user-images.githubusercontent.com/6793168/114762503-834eb600-9d6a-11eb-9a21-20f8f66036ba.png)

**Comment by akimdi** [comment] 2021-04-14 18:56
> The `trash` crate actually has a fully rust implementation of the freedesktop.org trash specification on the [`v2-dev`](https://github.com/ArturKovacs/trash-rs/tree/v2-dev) branch, maybe I should just replace the current implementation with that. thinking

It would be great 😀️

**Comment by ArturKovacs** [comment] 2021-04-14 19:04
> And I got this error, although emulsion still created .Trash-1000 folder and put a file in it, but emulsion froze.

Your idea was correct, but the problem is that your config file doesn't specify a key binding for the delete operation, in which case the default keybinding is used. So it seems that when you pressed the "delete" key emulsion ran the custom command first, and the attempted to delete the file using the built in mechanism but since the custom command already deleted the file, the built-in mechanism failed to locate the file.

If you want to prevent emulsion from trying to delete the file you should specify this in the config file:
```
img_del = []
```

**Comment by akimdi** [comment] 2021-04-14 19:12
> `img_del = []`

Thank you. I didn't know it.

**Comment by akimdi** [comment] 2021-05-01 01:01
@ArturKovacs 
With the release of versions 9.0, no files are deleted at all 😥️
`Error while moving file '"./1.webp"' to trash: Unknown { description: "Path: \'\"/home/me/.local/share/Trash/info/1.webp.trashinfo\"\'. Message: No such file or directory (os error 2)" }`

**Comment by akimdi** [comment] 2021-05-01 01:03
I rolled back to version 8

**Comment by ArturKovacs** [comment] 2021-05-01 08:43
@akimdi could you try building and running emulsion from the `fix-cant-delete` branch? If it doesn't work then please `cd` into where you built the executable (`target/debug` or `target/release`) and run emulsion with
```
RUST_LOG=debug ./emulsion
```

Then try deleting a file and paste the output into a comment here.

**Comment by akimdi** [comment] 2021-05-02 00:02
Now everything works. Thank you 😀️👍️
[`fix-cant-delete`](https://github.com/ArturKovacs/emulsion/tree/fix-cant-delete)

**Closed** 2021-05-02 08:39 UTC
Labels: (a) bug, (c) Linux
