### ISSUE TITLE
Do you think it is necessary to add an icon that will inform about the loading of a large image? 

### ISSUE THREAD

**Issue by akimdi** [ArturKovacs/emulsion#197] opened 2021-05-01 00:48 UTC
example
https://upload.wikimedia.org/wikipedia/commons/1/1f/Geneva_from_Saleve_0.jpg

**Comment by ArturKovacs** [comment] 2021-05-01 07:25
Closing as this is a duplicate of #25

**Closed by ArturKovacs** 2021-05-01 07:25 UTC
Labels: (a) enhancement, (z) duplicate
