### ISSUE TITLE
Image shows up black in Emulsion, but not in other viewers

### ISSUE THREAD

**Issue by Qwerty-Space** [ArturKovacs/emulsion#99] opened 2020-06-14 02:01 UTC
![image](https://user-images.githubusercontent.com/6967592/84582976-1c2f4080-adeb-11ea-833e-6d223a9bf1ab.png)
Not sure if there's any logs or anything, but this image opens all right in FastStone.  It's a stupidly large image (30000x30000 218MB), so that might affect it.

It's a JPEG with (obviously) no transparency

**Comment by Shnatsel** [comment] 2020-06-14 16:24
Could you share the image that's causing this? Perhaps upload it to mega.nz or some such?

**Comment by ArturKovacs** [comment] 2020-06-14 17:27
I don't think having access to the specific image would help in this case. A 30,000x30,000 pixel image takes up more than 2.5 GBs of GPU memory. Not many people have a gpu that have that amount of storage. For example I don't. So even if the file can be decoded by emulsion it won't be possible to render it, using the current architecture.

This could be solved by only uploading a downscaled version to the gpu. Then as you zoom in, just the portion visible on the screen could be uploaded at a higher resolution.

This is relatively time consuming to implement but i can't think of a better way. Also this must obviously be done in a way that it doesn't have a significant impact on the loading time of smaller images.

**Comment by Shnatsel** [comment] 2020-06-14 17:31
I do in fact have enough of GPU memory to do that. But what I really wanted to check is whether this is a bug in `image` - perhaps the image is already decoded incorrectly before it even gets to `emulsion` code.

**Comment by Shnatsel** [comment] 2020-06-14 17:40
I can reproduce this with a 30,000x10,000 image I generated myself, both JPG and PNG. I am also seeing the solid black rectangle instead of the image. GIMP reports 2.8Gb memory consumption for that image, so I it should fit in the amount of RAM that I have available.

**Comment by Shnatsel** [comment] 2020-06-14 17:53
`image` itself can load the files fine as far as I can tell. At least the included example that loads, downscales and writes the output to a file works correctly.

**Comment by ArturKovacs** [comment] 2020-06-14 18:01
Oh yes an there's also an upper limit for texture size in OpenGL. It is very likely that a texture with 30,000x10,000 pixels is larger than the maximum allowed size. (This maximum size depends on the specific GPU and driver)

**Comment by Qwerty-Space** [comment] 2020-06-14 18:47
> 
> 
> I don't think having access to the specific image would help in this case. A 30,000x30,000 pixel image takes up more than 2.5 GBs of GPU memory. Not many people have a gpu that have that amount of storage. For example I don't. So even if the file can be decoded by emulsion it won't be possible to render it, using the current architecture.
> 
> This could be solved by only uploading a downscaled version to the gpu. Then as you zoom in, just the portion visible on the screen could be uploaded at a higher resolution.
> 
> This is relatively time consuming to implement but i can't think of a better way. Also this must obviously be done in a way that it doesn't have a significant impact on the load-time of smaller images.

I have a GTX 970, 4 GB of VRAM

**Comment by Qwerty-Space** [comment] 2020-06-14 18:48
> 
> 
> I can reproduce this with a 30,000x10,000 image I generated myself, both JPG and PNG. I am also seeing the solid black rectangle instead of the image. GIMP reports 2.8Gb memory consumption for that image, so I it should fit in the amount of GPU Rem that I have available.

Do you still want the file?

**Comment by Shnatsel** [comment] 2020-06-14 18:50
Not anymore. I've managed to reproduce it with the files I generated myself. But thanks!

**Comment by Aloso** [comment] 2020-06-16 17:50
This is the function that estimates the size of image frames:

```rust
pub fn get_image_size_estimate(dimensions: (u32, u32)) -> u32 {
    // counting all the mipmaps would add an additionnal multiplier of around ~1.6
    // but only the gpu textures have mip maps so just multiply by 1.5
    ((dimensions.0 * dimensions.1 * 4) as f32 * 1.5) as u32
}
```

That's 30,000 × 30,000 × 4 × 1.5 = 5,400,000,000 = 5.4 GB, which is more than your 4 GB of VRAM.

Note that the conversion to `u32` overflows, but that shouldn't cause the described bug.

**Comment by ArturKovacs** [comment] 2020-06-16 19:02
Again, the issue is most likely the texture size limitation and not even the VRAM size.

You can check the maximum size along a single dimension that's allowed for a texture, by running the following javascript in your preferred browser's console.

```javascript
var canvas = document.createElement('canvas');
var gl = canvas.getContext("webgl");
gl.getParameter(gl.MAX_TEXTURE_SIZE)
```

For me, this gives `16384` meaning that my GPU and driver does not support textures that are bigger than `16384*16384` pixels.

**Comment by Aloso** [comment] 2020-06-16 23:57
Oh, it's only 8192 for me :D

**Comment by ArturKovacs** [comment] 2020-06-17 08:28
Hmm I just realized that this context *might* be attached to the integrated GPU instead of the dedicated GPU. But Emulsion should use the integrated GPU anyways so in that case those numbers give us a good idea of the upper limit.

**Comment by Qwerty-Space** [comment] 2020-06-19 23:25
> 
> 
> Again, the issue is most likely the texture size limitation and not even the VRAM size.
> 
> You can check the maximum size along a single dimension that's allowed for a texture, by running the following javascript in your preferred browser's console.
> 
> ```js
> var canvas = document.createElement('canvas');
> var gl = canvas.getContext("webgl");
> gl.getParameter(gl.MAX_TEXTURE_SIZE)
> ```
> 
> For me, this gives `16384` meaning that my GPU and driver does not support textures that are bigger than `16384*16384` pixels.

Oh so that could be why it crashes in fullscreen in other viewers, but not in windowed?

**Comment by Qwerty-Space** [comment] 2020-06-19 23:27
> 
> 
> Hmm I just realized that this context _might_ be attached to the integrated GPU instead of the dedicated GPU. But Emulsion should use the integrated GPU anyways so in that case those numbers give us a good idea of the upper limit.

Why not use the dedicated GPU if available?

**Comment by ArturKovacs** [comment] 2020-06-20 07:01
> Oh so that could be why it crashes in fullscreen in other viewers, but not in windowed?
16384 here

That's a weird combination; I don't know why that happens.

> Why not use the dedicated GPU if available?

Let me backtrack a little bit. In order of priority Emulsion...

1.  should display 60 FPS while updating the screen
2. should use the GPU that has the lowest power consumption while satisfying (1)

So the argument for using the integrated GPU when a dedicated is available is to minimize power consumption. It's very situation dependet which one is better; but luckily for us it seems that this decision can be made by the GPU driver on-the-fly (See AMD Switchable Graphics and Nvidia Optimus).

**Comment by Qwerty-Space** [comment] 2020-06-20 14:18
Oh fair enough. Would be nice if there was a setting for it, considering power consumption isn't a worry for some

**Comment by ArturKovacs** [comment] 2020-06-20 15:02
As far as I know it is possible to set manually. It's sometimes among the other driver settings but it may be hidden to a configuration file somewhere. So I'm pretty sure you'll find something if you around online.

**Comment by ArturKovacs** [comment] 2020-09-12 18:47
A little update on this:

The funny situation is that glium's texture creation does not give an error if the uploaded image is larger than the maximum supported size. All it does

**Comment by ArturKovacs** [comment] 2021-04-11 20:35
@Qwerty-Space could you test the [`big-img`](https://github.com/ArturKovacs/emulsion/tree/big-img) branch? The behavior might very well be driver/device dependent. I tried it on my computer and it only displayed part of the image but to the best of my knowledge there's not much else that can be done to make this work on a GPU.

**Comment by Shnatsel** [comment] 2021-04-11 20:48
Yep, can confirm a huge png (20,000 by 400 px) works for me on this branch. My GPU only supports 16384px wide textures assuming the WebGL info is accurate.

**Comment by Shnatsel** [comment] 2021-04-11 20:48
File used for testing: [huge.png](https://user-images.githubusercontent.com/291257/114320803-05936c00-9b18-11eb-8d97-2fb0bfb95637.png)

**Comment by ArturKovacs** [comment] 2021-04-11 21:01
If I not mistaken, that image should also work with the master branch, because I think that 16384 means that your gpu supports textures of at most 16384^2 pixels which can also be a 1px*268,435,456px texture.

I would try it with a 20,000 by 17,000 px image. But I may be wrong. Again if the one you tried doesn't work on the master branch, that's already a success 😄

**Comment by Shnatsel** [comment] 2021-04-11 21:10
Yeah, that same image doesn't work on master.

**Comment by Qwerty-Space** [comment] 2021-04-11 22:25
> @Qwerty-Space could you test the [`big-img`](https://github.com/ArturKovacs/emulsion/tree/big-img) branch? The behavior might very well be driver/device dependent. I tried it on my computer and it only displayed part of the image but to the best of my knowledge there's not much else that can be done to make this work on a GPU.
> 
> EDIT: Although now that I think about it, there's probably a way, but maybe not with glium :(

I've got a whole new PC now, but I can try

**Comment by ArturKovacs** [comment] 2021-04-12 07:18
> I've got a whole new PC now, but I can try

If you are still interested in resolving the issue, you should try. If not, which is also completely fine, just let me know and I'll call this done.

**Comment by Qwerty-Space** [comment] 2021-04-13 13:51
> @Qwerty-Space could you test the [`big-img`](https://github.com/ArturKovacs/emulsion/tree/big-img) branch? 

How do I install it?

**Comment by ArturKovacs** [comment] 2021-04-13 14:38
If you have Rust installed, the workflow is that you clone this repo, then checkout the `big-img` branch then execute `cargo run --release` at the root of the repo. (Note that it takes a good 10 minutes to compile a release build) If you don't want to install Rust, I can give you a Windows installer from under the counter, just let me know.

**Comment by GbGp** [comment] 2021-04-18 12:29
Hi, I tried the big-img branch on [this](https://user-images.githubusercontent.com/59691707/115145424-bb4b4700-a051-11eb-9d3d-aaa7919fd75b.png) 20000x20000 image (it's just B&W checkerboard). It works very well but it takes 1:30 to load the image (in contrast my browser or gimp can do it in few secs).
On my system MAX_TEXTURE_SIZE is 16384.

**Comment by ArturKovacs** [comment] 2021-04-18 12:39
Hi @GbGp!

Did you run it in release mode? (`cargo run --release` or  `cargo build --release`)

**Comment by GbGp** [comment] 2021-04-18 12:59
no sorry, it was a debug build. Tried again with --release and it's pretty fast.

**Closed** 2021-04-27 06:43 UTC
Labels: (a) enhancement, (b) image-displaying, (y) priority
