### ISSUE TITLE
Loading invalid image freezes X server

### ISSUE THREAD

**Issue by kneasle** [ArturKovacs/emulsion#186] opened 2021-03-06 12:25 UTC
I've somehow ended up with a ton of broken `.png` files in my screenshots folder and when emulsion tries to open them the X server freezes for an indeterminate amount of time.  Sometimes I do regain control after perhaps 30 seconds, but this is inconsistent.  It's not a full system freeze, because Spotify keeps playing like a champ in the background - it's just that my window manager (herstluftwm if that helps at all) stops working (and possibly also the underlying X server).

Also, I'm really struggling to figure out what's actually going on because doing any kind of debugging requires my window manager to be responsive.  My suspicion is that the problem is something like the main thread blocking on the image loading and therefore also blocking herbstluftwm's main thread.  But I have really no idea.  Has anyone else experienced this, I wonder?

**Comment by kneasle** [comment] 2021-03-06 12:26
Or does anyone have more specific ideas/pointers for where the problem might be occuring in the code?

**Comment by ArturKovacs** [comment] 2021-03-06 12:56
This is related to #172. I already invested some time in this and this issue is driving me nuts. I currently don't even have a good idea for finding the cause of this bug.

**Comment by ArturKovacs** [comment] 2021-03-06 12:57
Closing due to being a duplicate.

**Closed by ArturKovacs** 2021-03-06 12:57 UTC
Labels: (a) bug, (c) Linux, (z) duplicate
