### ISSUE TITLE
Opening a PNG locks up the entire X server

### ISSUE THREAD

**Issue by Shnatsel** [ArturKovacs/emulsion#172] opened 2021-01-24 21:44 UTC
Steps to reproduce:

1. Put the attached image in a folder with at least 1 other image
2. Open the attached image in Emulsion; it fails to decode.
3. Use the arrow keys to switch back and forth between the attached image and some other image. 

Switching to this image takes longer with each switch. While Emulsion is frozen, the rest of the GUI also does not respond, but I can switch to kernel console with Ctrl+Alt+F1.

My window manager also runs on OpenGL, not sure if that's relevant.

Tested on Ubuntu 18.04, AMDGPU driver, both stock configuration and the more recent [hardware enablement stack](https://wiki.ubuntu.com/Kernel/LTSEnablementStack). Since both configurations are affected, I suspect this is an issue with Emulsion.

**Comment by Shnatsel** [comment] 2021-01-24 21:44
![1443708892 angelfonds_1443660918 crazybear_05ccadee-c566-4e25-9046-f4a437530a2d](https://user-images.githubusercontent.com/291257/105644405-b2edd080-5e95-11eb-8136-2752511ad781.png)

**Comment by totikom** [comment] 2021-01-25 13:46
This behavior also reproduces on latest Manjaro GNOME with linux  5.4.89.
`stderr` shows this:

> Request #2: Error occurred while loading file "<path to the abovementioned image>.png"
> Format error decoding Png: compressed data stream corrupted
> Error occurred while loading image: Failed to load #2

**Comment by ArturKovacs** [comment] 2021-01-31 11:39
I bisected this and the first bad commit is 3ece1cf3767729a9fcdd133e6a15b2abf76001e7

I tried undoing the effect of those changes by hand on top of master but no matter what I try it doesn't seem to make issue go away. And yet the commit before the one specified does not freeze the system just prints an error message.

Debugging this issue is very tiresome as often `pkill`-ing emulsion isn't enough to un-freeze the system so I have to restart which takes a while on my machine. I'll probably get back to this later. But if someone would like to investigate I would be more than happy to pass this on.

**Comment by ArturKovacs** [comment] 2021-04-15 19:02
I just tested this and I did get the image loading failure but both emulsion and my desktop remained responsive. I believe there are two important differences since last time I tested:
- Last time I had GNOME. This time, KDE.
- I believe the version of winit was updated since then.

I don't currently have a GNOME. Could you please test again, the latest commit from the master and report back?

**Comment by Shnatsel** [comment] 2021-04-15 20:15
Still hangs for me on the same system that I originally reported this from. Latest master (commit 69b0f6e5937f3cff3b7170a885690d474ebd79d0) even after a `cargo update`

**Comment by ArturKovacs** [comment] 2021-04-15 22:59
I encountered this issue while working on another problem. #191 *seems* to fix it for me but I'm not sure about anything at this point :D Could you try that out and see what it does for you?

**Comment by Shnatsel** [comment] 2021-04-15 23:16
Oh yeah, that fixed it! Finally!

**Comment by ArturKovacs** [comment] 2021-04-26 22:59
Fixed in #191

**Closed by ArturKovacs** 2021-04-26 22:59 UTC
Labels: (a) bug, (c) Linux
